purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.4915683
  brandStrength: 1
  lightness: 0.505059
  brandColors:
    - '#FFFFFF'
    - '#353535'
    - '#B7B5B6'
    - '#857365'
    - '#813734'
  rhythmicContrast: 0
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
cta:
  bucket: null
  version: null
  domain: null
name: Life LDC
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.5168634
layout_spectrum: 0.6728499
